name: Install AWS CLI, kubectl, and eksctl

on:
  workflow_dispatch: # This event allows manual triggering from the GitHub UI
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  deploy-eks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region eu-central-1
      
      - name: Install kubectl
        run: |
          sudo snap install kubectl --classic
          mkdir ~/.kube
          kubectl version --client
      
      - name: Install eksctl
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          eksctl version
      
      - name: Install juju
        run: |
          sudo snap install juju --classic
          juju version
      
      - name: Create cluster
        run: |
          eksctl create cluster -f .github/workflows/cluster.yaml
          kubectl get nodes
      
      - name: Setup juju
        run: |
          juju add-k8s kubeflow --client
          juju bootstrap --no-gui kubeflow kubeflow-controller
          juju add-model kubeflow
      
      - name: Deploy mlflow bundle
        run: |
          juju deploy ./releases/latest/edge/mlflow/bundle.yaml --trust
          juju wait-for application mlflow-server --query='name=="mlflow-server" && (status=="active" || status=="idle")' --timeout=30m0s
          juju status --relations
      
      - name: Check MLflow running
        run: |
          kubectl -n kubeflow port-forward pod/mlflow-server-0 5000:5000 &
          kubectl -n kubeflow port-forward pod/mlflow-server-0 8000:8000 &
          sleep 5
          curl -I --fail localhost:5000
          curl -I --fail localhost:8000
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60
        if: failure()
      
      - name: Remove eks 
        if: always()
        run: |
          eksctl delete cluster --name=kubeflow-test 

